### ISSUE TITLE
[TASK] Replace Identity vars with generic OICD vars

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-platform-helm#1105]
**Related to:**

* Epic issue: https://github.com/camunda-cloud/identity/issues/2162
* Zeebe issue: https://github.com/camunda/zeebe/issues/15389

**Overview:**

Zeebe now integrates the `identity-spring-boot-autoconfig` dependency which can pick up Identity-specific configuration properties directly, and pass them to the Zeebe Gateway. 

**Actions:**

- [x] Replace the Zeebe configuration vars related to Identity (documented [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-config/#zeebegatewayclustersecurityauthenticationidentity)), with the dedicated Camunda Identity properties (documented [here](https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/)).
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1155
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1122
```

**Comment by aabouzaid** [comment]
@koevskinikola FYI, I've changed this task to the main task for all OICD vars changes (not only Zeebe).

**Comment by koevskinikola** [comment]
Thanks @aabouzaid.

Then I'll remove it from the ZPA project board, and assign @Ben-Sheppard to it.

**Comment by aabouzaid** [comment]
All PRs have been merged
