### ISSUE TITLE
[TASK] Expose Zeebe Gateway REST API port

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-helm#1228]
**Related to:**

https://github.com/camunda/zeebe/issues/15878

**Overview:**

Starting with 8.5, the Zeebe gateway (and possibly the broker via the embedded gateway) will have a new REST API port, 8080. This should be exposed in exactly the same way the 25600 port is, i.e. as a client facing port. As part of this change, the health probes path in the broker will also be updated (but for backwards compatibility, they will initially simply redirect).

**Actions:**

- [x] A new `rest` port is added to the Zeebe gateway deployment for port 8080
- [x] A new `rest` port is added to the Zeebe broker statefulset for port 8080, _only if the standalone gateway is not enabled_
- [x] Ingress is configured to handle this port (if required)
- [x] The probes for the Zeebe broker are updated to avoid running into redirects with the new routes

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1278
```

**Comment by npepinpe** [comment]
I could use your input on one particular decision. For some context, we will phase out the gRPC API such that it will become optional, and the default gateway API for Zeebe will be its REST API. This will happen in 8.7, with 8.6 being an interim release where both protocols are supported by default, and support all calls.

Since with 8.7, the default port/service will be REST, it would make sense to have `gatewayPort`, and `ingress` generally refer to that, since they're the default. However, that will be a breaking change at that point in time. If we changed it now, it would be a breaking change now.

So I see three options:

- Introduce new `zeebeGateway.service.restPort` and `zeebeGateway.service.restName` values. Also introduce a new `zeebeGateway.ingressRest` object which is basically the same as `zeebeGateway.ingress`. Everything else stays the same. With 8.7, we swap `restPort` and `restName` for `gatewayPort` and `gatewayName`, and introduce `grpcPort` and `grpcName`. Similarly, we swap `ingress` for `ingressRest`, and introduce a new `ingressGrpc`. So the breaking change occurs only in 8.7, but it requires changing multiple values, and may lead to confusion.
- Break now, and have `gatewayPort`, `gatewayName`, and `ingress` refer to the REST API. Introduce new values for the gRPC side under `grpcPort`, `grpcName`, and `grpcIngress`. This has the benefit that users only have to change with the next release, but the gRPC API is _required_ until 8.6 at least, possibly 8.7. Then they could potentially disable it if they want (which will be the default for new installations).
- Break now, but already make the division explicit: introduce `zeebeGateway.service.grpc.port`, `zeebeGateway.service.rest.port` (and homologous `name` values), and have `zeebeGateway.ingress.grpc` and `zeebeGateway.ingress.rest` values for the two ingresses. Later with 8.7, we can change the default for the gRPC stuff to be disabled. The advantage here is a clearer structure in the future, and only one breaking change.

I would lean towards the third option, but I will defer to you as to what you prefer. Please suggest another one if that fits better!

**Comment by npepinpe** [comment]
One more note, I added the `contextPath` support for the REST API. However, note that the management endpoints (e.g. `/actuator/*`), which includes the health probes, is unaffected as they are on a different port. This clashes with the other applications, so may break user expectations. _The management stuff does not support context path here_. I hope that's OK? :s

**Comment by aabouzaid** [comment]
@npepinpe it's fine because health endpoints so far are checked internally in the Pod.
We also have some other apps with the same behavior.

Maybe in the future, we rethink that to make the health checks available externally via Ingress or so.

The last step is to set `contextPath` so Zeebe Gateway itself knows its context.

**Comment by npepinpe** [comment]
We have two separate issues pending, but I'm marking this one as done. Everything's tracked in the epic anyway.
