### ISSUE TITLE
[EPIC]: Create CCSM Helm chart

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#123]
- [x] #124 
- [x] https://github.com/camunda-community-hub/camunda-cloud-helm/issues/128
- [x] https://github.com/camunda-community-hub/camunda-cloud-helm/issues/189
- [x] https://github.com/camunda-community-hub/camunda-cloud-helm/issues/179
- [x] #125 
- [x] https://github.com/camunda-cloud/camunda-cloud-documentation/issues/609
- [x] *Optional* #127 
- [x] ~*Optional* #126~ We will do this in upcoming quarter

**Comment by Zelldon** [comment]
We did this successfully
