### ISSUE TITLE
[EPIC]: Add Optimize Helm chart

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#126]
Add optimize chart to the single chart.

- [x] Requires: Identity in chart
- [x] Create a new sub chart in the ccsm-helm chart
  - [X] Add manifest templates for optimize https://github.com/camunda/camunda-platform-helm/pull/287
  - [X] Configure optimize to use identity https://github.com/camunda/camunda-platform-helm/pull/287
  - [x] https://github.com/camunda/camunda-platform-helm/issues/286
- [x] https://github.com/camunda/camunda-platform-helm/issues/289
- [x] Add possible configurations as values to the [values.yaml](charts/ccsm-helm/values.yaml) file
- [x] Verify default resources with SaaS G3-s https://github.com/camunda/camunda-platform-helm/issues/298
- [x] Document the configurations in values file and readme
  - [x] https://github.com/camunda/camunda-platform-helm/issues/284
- [x] https://github.com/camunda/camunda-platform-helm/issues/299
- [x] Test optimize sub chart
  - [X] Add template tests https://github.com/camunda/camunda-platform-helm/pull/287
  - [x] https://github.com/camunda/camunda-platform-helm/issues/283
- [x] Update architecture image, you can find the source in google drive. zeebe/ccsm-helm/CCSM Helm Architecture Image.
  - [x] https://github.com/camunda/camunda-platform-helm/issues/285
- [x] Add documentation about optimize to the camunda docs 
  - [x] Update architecture image and mention in self-managed section https://github.com/camunda-cloud/camunda-cloud-documentation/pull/849
  - [x] Created follow up issue to improve Optimize docs https://github.com/camunda-cloud/camunda-cloud-documentation/issues/845

Depends on #127

**Comment by Zelldon** [comment]
For visibility, I raised the following in slack:

> :warning: Request for feedback/input
> 
> I'm working on the Optimize integration and found some things I would like to discuss.
> 
> - Optimize needs to be configured with the partition count. Currently, this information is located in the Zeebe sub-chart. Helm doesn't allow sharing of information between child /sub-charts. The following solutions I see:
>   - We add a new property, which is globally available. Like: global.zeebePartitionCount The problem I see here is that currently, we have zeebe.partitionCount which people use. We could drop the property and print a warning if this property is still in use. If we want to keep the value: we could use the value of global.zeebePartitionCount in zeebe.partitionCount, to only configure one property. But this will not help with users which already use zeebe.partitionCount and are not aware of the new property.
>   - We add just a new property in the Optimize sub chart and the user needs to configure the partition count in two places. In zeebe and optimize section.
>   - I could investigate an idea I had recently. In the root we have access to all properties, so we might be able to deploy a config map for Optimize, which contains the properties from Zeebe. 
>   - Optimize can somehow self-detect the partition count like operate does
> - Optimize has a dependency on identity. What if identity is disabled? Should we disable Optimize as well? Might make sense to me.
> - We currently have identity.enabled to enable and deploy identity resources and global.identity.auth.enable to enable the authentication for all web apps with identity. Currently you have to disable both to run operate or tasklist without identity (and not deploy identity resources). Do we want to combine them? Like only having global.identity.auth.enable and removing identity.enabled . This would be a breaking change, but I don't expect too many problems with that.

**Comment by Zelldon** [comment]
Done via https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.0.5
