### ISSUE TITLE
[TASK] Enhance Helm chart version matrix

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1696]
**Related to:**

Epic: https://github.com/camunda/distribution/issues/148

**Overview:**

For smooth operations and upgrades, we need to ensure that the Helm CLI version we used in the tests and release is visible to the end user.
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-docs/pull/3724
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1716
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1742
```
