### ISSUE TITLE
[TASK] Expose Camunda license for all components

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1813]
## Related to

Epic: https://github.com/camunda/distribution/issues/230

## Overview

We have changed the license recently and moved to use [Zeebe as a mono repo](https://github.com/camunda/zeebe) for all/most Camunda components. So now we need to provide a single place that has the Camunda license.

This feature is needed for the 8.6 release only (alpha chart).

## Actions

```[tasklist]
### Sub-tasks
- [x] Add license resources like values file structure and templates (it should be a K8s secret)
- [x] Pass license resources to all Camunda [components](https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform/templates)
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2053
```

**Comment by aabouzaid** [comment]
Done :heavy_check_mark:
