### ISSUE TITLE
[ENHANCEMENT] Inconsistent inputs for existingSecret

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1898]
# Enhance Secret Key Handling (Target: 8.8)

## Summary

As discussed with the team:

- This change enhancemes **only version 8.8** (no changes for earlier versions).
- Introduces a **new, standardized format** for secret and keys that supports both production and non-production use cases.
- Ensures this is a **non-breaking change**:
  - If new secret/ keys are set → use them
  - If not → fallback to old/deprecated keys
- If a string literal (e.g., `.secret.password`) is used, **log a warning** that this is not recommended for production.
- **Deprecate old keys in 8.8**, and plan their **removal in 8.9**

### Secret Value Convention

```yaml
# Valid non-production usage:
[...].secret.password: "plain-text-password"

# Valid production usage (Kubernetes secret reference):
[...].secret.existingSecret: "k8s-secret-name"
[...].secret.existingSecretKey: "optional-key"
```

## 🛠 Acceptance Criteria

- [x] For all internal and external (non-subchart) secrets:
  - [x] Support for `.secret.password`
  - [x] Support for `.secret.existingSecret`
  - [x] Support for `.secret.existingSecretKey`

- [x] Add fallback logic to use deprecated key/value if new keys are not set

- [x] Add log warning if `.secret.password` is used (non-production usage warning)

- [x] Deprecate old secret keys (mark in Helm values.yaml, comments and docs announced):
  - [x] Mark `identity.firstUser.password` as deprecated
  - [x] Mark other old keys listed in the spec as deprecated

- [x] Add Helm schema validation if applicable (e.g., warn when both old and new keys are set)

- [x] Add unit tests for new secret handling:
  - [x] Test production scenario (existingSecret & key)
  - [x] Test non-production scenario (password string)
  - [x] Test fallback scenario (only old key defined)
  - [x] Test invalid combinations

- [x] Update [Secret Management Guide](https://docs.camunda.io/docs/next/self-managed/setup/guides/secret-management/) to:
  - [x] Introduce new `.secret.*` structure
  - [x] Explain fallback behavior
  - [x] Add production vs non-production best practices
  - [ ] Change in announcement and update guide

#### Identity First User Password

- [x] `identity.firstUser.password` → `identity.firstUser.secret.password`
- [x] `identity.firstUser.existingSecret` → `identity.firstUser.secret.existingSecret`
- [x] ➕ `identity.firstUser.secret.existingSecretKey`

#### OAuth Client Secret (Optimize)

- [x] `global.identity.auth.optimize.existingSecret.name` → `global.identity.auth.optimize.secret.existingSecret`
- [x] ➕ `global.identity.auth.optimize.secret.existingSecretKey`
- [x] ➕ `global.identity.auth.optimize.secret.password`

#### OAuth Client Secret (Connectors)

- [x] `global.identity.auth.connectors.existingSecret.name` → `global.identity.auth.connectors.secret.existingSecret`
- [x] ➕ `global.identity.auth.connectors.secret.existingSecretKey`
- [x] ➕ `global.identity.auth.connectors.secret.password`

#### OAuth Client Secret (Console)

- [x] `global.identity.auth.console.existingSecret.name` → `global.identity.auth.console.secret.existingSecret`
- [x] ➕ `global.identity.auth.console.secret.existingSecretKey`
- [x] ➕ `global.identity.auth.console.password`

#### OAuth Client Secret (Core)

- [x] `global.identity.auth.core.existingSecret.name` → `global.identity.auth.core.secret.existingSecret`
- [x] ➕ `global.identity.auth.core.secret.existingSecretKey`
- [x] ➕ `global.identity.auth.core.secret.password`

#### Enterprise License Key

- [x] `global.license.existingSecret` → `global.license.secret.existingSecret`
- [x] `global.license.existingSecretKey` → `global.license.secret.existingSecretKey`
- [x] ➕ `global.license.secret.password`

### External Database Password (Web Modeler)

- [x] `webModeler.restapi.externalDatabase.existingSecret.name` → `webModeler.restapi.externalDatabase.secret.existingSecret`
- [x] ➕ `webModeler.restapi.externalDatabase.secret.existingSecretKey`
- [x] ➕ `webModeler.restapi.externalDatabase.secret.password`

#### SMTP Password (Web Modeler)

- [x] `webModeler.restapi.mail.existingSecret.name` → `webModeler.restapi.mail.secret.existingSecret`
- [x] ➕ `webModeler.restapi.mail.secret.existingSecretKey`
- [x] ➕ `webModeler.restapi.mail.secret.password`

#### Connectors Inbound Auth Password

- [x] `connectors.inbound.auth.existingSecret` → `connectors.inbound.auth.secret.existingSecret`
- [x] ➕ `connectors.inbound.auth.secret.existingSecretKey`
- [x] ➕ `connectors.inbound.auth.secret.password`

#### External Elasticsearch Auth

- [x] `global.elasticsearch.auth.existingSecret` → `global.elasticsearch.auth.secret.existingSecret`
- [x] ➕ `global.elasticsearch.auth.secret.existingSecretKey`
- [x] ➕ `global.elasticsearch.auth.secret.password`

#### External Elasticsearch TLS Cert

- [x] `global.elasticsearch.tls.existingSecret` → `global.elasticsearch.tls.secret.existingSecret`
- [x] ➕ `global.elasticsearch.tls.secret.existingSecretKey`
- [x] ➕ `global.elasticsearch.tls.secret.password`

#### External OpenSearch Auth

- [x] `global.opensearch.auth.existingSecret` → `global.opensearch.auth.secret.existingSecret`
- [x] ➕ `global.opensearch.auth.secret.existingSecretKey`
- [x] ➕ `global.opensearch.auth.secret.password`

#### External OpenSearch TLS Cert

- [x] `global.opensearch.tls.existingSecret` → `global.opensearch.tls.secret.existingSecret`
- [x] ➕ `global.opensearch.tls.secret.existingSecretKey`
- [x] ➕ `global.opensearch.tls.secret.password`

--- 

<details>

<summary>Prior ticket description and problem statement (updated on 2025-05-27)</summary>

**Describe the use case:**

[SUPPORT-23070](https://jira.camunda.com/browse/SUPPORT-23070)

Hey all, I'm using this ticket as a way of documenting all of the different usages of `existingSecret` and which format they accept as input.  This github issue is for tracking the inconsistency between the different usages.

## Existing references

| Path in values.yaml  | Expected input | Is subchart |
| ------------- | ------------- | ------------------- |
| global.elasticsearch.tls.existingSecret  | Name of k8s secret (string)  | No |
| global.elasticsearch.auth.existingSecret  | Name of k8s secret (string)  | No |
| global.opensearch.tls.existingSecret | Name of k8s secret (string) | No |
| global.opensearch.auth.existingSecret | Name of k8s secret (string) | No |
| global.identity.auth.connectors.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| global.identity.auth.identity.existingSecret | explicit password (string) or K8s Secret under name subkey (map)  | No |
| global.identity.auth.operate.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| global.identity.auth.tasklist.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| global.identity.auth.optimize.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| global.identity.auth.console.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| global.identity.auth.zeebe.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| global.identity.auth.connectors.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| identity.firstUser.existingSecret | Name of k8s secret (string) | No |
| identity.externalDatabase.existingSecret |  Name of k8s secret (string) | No |
| connectors.inbound.auth.existingSecret | Name of k8s secret (string) | No |
| webModeler.restapi.externalDatabase.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |
| webModeler.restapi.mail.existingSecret | explicit password (string) or K8s Secret under name subkey (map) | No |

## Existing references in subcharts

| Path in values.yaml  | Expected input | Is subchart |
| ------------- | ------------- | ------------------- |
| identityPostgresql.auth.existingSecret | Name of k8s secret (string) | Yes |
| identityKeycloak.auth.existingSecret | Name of k8s secret (string) | Yes |
| postgresql.auth.existingSecret | Name of k8s secret (string) | Yes |
| global.identity.keycloak.auth.existingSecret | Name of k8s secret (string) | Yes |

**Describe the enhancement/feature:**

Ideally, we should be using the same sort of input formats everywhere, however, we  have some limitations:

1. It's difficult to configure support for `existingSecret` AND `existingSecret.name`
2. We do not get to modify how subcharts specify their own values.yaml's
3. Changes we do would be considered a breaking change.

**Desired outcome and acceptance tests:**

* [ ] As a user I have a consistent and clear way to set all my secrets

### Tasks

* [x] https://github.com/camunda/camunda-platform-helm/issues/3012
* [x] Research and potentially simplify / consolidate to use existingSecret (instead of existingSecret.name)
* [ ] Consistent secret handling is documented and implemented.
</details>

PR: https://github.com/camunda/camunda-platform-helm/pull/3838

### Follow ups

* Consider refactoring for console tls and document store secrets
* Understand and document auto generated secrets

**Comment by hamza-m-masood** [comment]
Currently some of the comments are vague for exsitingSecret values. It is not clear whether an existingSecret can be provided from k8s or an explicit string including the password is needed. Example: https://github.com/camunda/camunda-platform-helm/blob/337e4c877149f817d3d10d83ea2de425da4ed524/charts/camunda-platform-latest/README.md?plain=1#L491

**Comment by ingorichtsmeier** [comment]
Hi @jessesimpson36, there is another issue/inconsistency. 

The password for `global.postgresql.auth.password` is not mentioned in your list.

Upgrading without it shows this error:

```
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.postgresql.auth.password' must not be empty, please add '--set global.postgresql.auth.password=$PASSWORD' to the command. To get the current value:

        export PASSWORD=$(kubectl get secret --namespace "camunda-platform" camunda-platform-postgresql -o jsonpath="{.data.password}" | base64 -d)
```

The error message disappears after adding

```
global:
  postgresql:
    auth:
      password: 65IkdkT9eE
      postgresPassword: brIgMHUJ7X
```

But it requires the Admin password for the Keycloak PostgresQL database as well.

**Comment by MaxTru** [comment]
This issue was mentioned by an important customer, see https://jira.camunda.com/browse/SUPPORT-22046

**Comment by Langleu** [comment]
`webModeler.restapi.externalDatabase.existingSecret` found this one super confusing as one has to read the `helpers.tpl` to understand how it's configured as the relevant docs just state:

```
## @param webModeler.restapi.externalDatabase.existingSecret can be used to provide the name of an existing secret resource containing the database password
      existingSecret:
```

**Comment by hisImminence** [comment]
As discussed with the team. We aim to get this enhancement merged for 8.8 and will not backport this to prior versions. This will be a non-breaking change via introducing a new, standard keys to set and define secrets, and deprecating the old keys (remove with 8.9).:

```
secret.password: "passwordAsString" <-- use case non-production
secret.existingSecret: "nameOfK8sSecret" <--use case production
```

Both use cases have been validated by PM and consultants and are valid. We will use the new keys if a value is set, else fall back to deprecated key/value.

### Concrete changes

The secrets to be adjusted are (regarding the [secret management guide](https://docs.camunda.io/docs/self-managed/setup/guides/secret-management/)):

**Legend**
❌ : no work/ adjustment needed
👷 : work/ adjustment needed

---

* ❌: **Keycloak Admin Password**
   * `identity.keycloak.auth.existingSecret` <-- no change as subchart

* 👷: **Identity First User Password**
   * `identity.firstUser.password`
      * adjust: `identity.firstUser.secret.password`
   * `identity.firstUser.existingSecret`
      * adjust: `identity.firstUser.secret.existingSecret`

* 👷: **OAuth Client Secret (Operate)**
   *  `global.identity.auth.operate.existingSecret.name` 
      * adjust: `global.identity.auth.operate.secret.existingSecret`
      * add: `global.identity.auth.operate.secret.password`

* 👷: **OAuth Client Secret (Tasklist)**
   * `global.identity.auth.tasklist.existingSecret.name`
      * adjust: `global.identity.auth.tasklist.secret.existingSecret`
      * add: `global.identity.auth.tasklist.secret.password`

* 👷: **OAuth Client Secret (Optimize)**
   * `global.identity.auth.optimize.existingSecret.name`
      * adjust: `global.identity.auth.optimize.secret.existingSecret`
      * add: `global.identity.auth.optimize.secret.password` 

* 👷: **OAuth Client Secret (Connectors)**
   * `global.identity.auth.connectors.existingSecret.name`
      * adjust: `global.identity.auth.connectors.secret.existingSecret`
      * add: `global.identity.auth.connectors.secret.password`

*👷: **OAuth Client Secret (Console)**
   * `global.identity.auth.console.existingSecret.name`
      * adjust: `global.identity.auth.console.secret.existingSecret`  
      * add: `global.identity.auth.console.password`

* 👷: **OAuth Client Secret (Zeebe)**
   * adjust: `global.identity.auth.zeebe.secret.existingSecret`
   *  add: `global.identity.auth.zeebe.secret.password`

* 👷: **Enterprise License Key**
   * `global.license.existingSecret`
      * adjust: `global.license.secret.existingSecret`
      * add: `global.license.secret.password`
   * `global.license.existingSecretKey` 
      * adjust: `global.license.secret.existingSecretKey`

* ❌: Identity PostgreSQL Password
   * `identityPostgresql.auth.existingSecret` <-- no change as subchart

* ❌: Keycloak PostgreSQL Password
   * `identityKeycloak.auth.existingSecret` <-- no change as subchart

* ❌: Web Modeler PostgreSQL Password
   * `postgresql.auth.existingSecret` <-- no change as subchart

**External secrets**

* 👷: **External Database Password**
   * `webModeler.restapi.externalDatabase.existingSecret.name`
      * adjust:`webModeler.restapi.externalDatabase.secret.existingSecret`  
      * add: `webModeler.restapi.externalDatabase.secret.password`

* 👷: **SMTP Password**
   * `webModeler.restapi.mail.existingSecret.name`
      * adjust: `webModeler.restapi.mail.secret.existingSecret`
      * add: `webModeler.restapi.mail.secret.password`

* 👷: **Connectors Inbound Auth Password**
   * `connectors.inbound.auth.existingSecret`
      * adjust: `connectors.inbound.auth.secret.existingSecret`
      * add: `connectors.inbound.auth.secret.password`
      * add: `connectors.inbound.auth.secret.existingSecretKey`

* 👷: **External Elasticsearch Auth**
   * `global.elasticsearch.auth.existingSecret`
      * adjust: `global.elasticsearch.auth.secret.existingSecret`
      * add: `global.elasticsearch.auth.secret.password`

* 👷: **External Elasticsearch TLS Cert**
   * `global.elasticsearch.tls.existingSecret`
      * adjust: `global.elasticsearch.tls.secret.existingSecret`
      * add: `global.elasticsearch.tls.secret.password`

* 👷: **External OpenSearch Auth**
   * `global.opensearch.auth.existingSecret`
      * adjust: `global.opensearch.auth.secret.existingSecret`
      * add: `global.opensearch.auth.secret.password`

* 👷: **External OpenSearch TLS Cert**
   * `global.opensearch.tls.existingSecret`
      *  adjust: `global.opensearch.tls.secret.existingSecret`
      * add: `global.opensearch.tls.secret.password`

**Comment by hisImminence** [comment]
@aabouzaid could you please review the above and confirm that this is the work needed and what we should do?

**Comment by aabouzaid** [comment]
@hisImminence That looks exactly what we need 👌

**Comment by hisImminence** [comment]
super thanks @aabouzaid!

@theburi fyi - this would then be our proposal for the secret configuration moving forward (for >=8.8). Do you have have any feedback on this proposal? Else we can move this ticket to ready.

**Comment by hisImminence** [comment]
Thank you all. I adjusted the body of the ticket and will mark it as ready now 🎉

**Comment by hisImminence** [comment]
related: https://github.com/camunda/camunda-platform-helm/issues/3695
