### ISSUE TITLE
[TASK] Support optional auto-generate of chart secrets

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1983]
## Related to

Epic: https://github.com/camunda/distribution/issues/125

## Overview

As we move to avoid generating secrets to enhance the upgrade process, we still need to support an optional auto-generation of chart secrets.

That way we will avoid any manual actions to install the chart.

## Actions

We can have an optional flag to auto-generate 1 secret object that has all secrets and utilize the Helm hooks to ensure that the secret is not part of the deployment namely `helm.sh/hook: pre-install` and `helm.sh/resource-policy: keep` so it will not be deleted or touched.

```[tasklist]
### Sub-tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2257
- [x] https://github.com/camunda/camunda-platform-helm/commit/6971f820547cf3f6377e253475f11f8f529074f5
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2288
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2290
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2293
```

**Comment by aabouzaid** [comment]
It's a bit hard to support that feature on older charts like 8.3 and 8.2 so this task is done and it's part of the charts `version:9.4.0`
and `version:10.4.0` and 8.6 chart will be released in October.
