### ISSUE TITLE
[ENHANCEMENT] add native support for Identity CORS configuration

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#2015]
**Describe the use case:**

This [issue](https://github.com/camunda/issues/issues/648) `Invalid CORS Request` is frequently occurring, especially with AWS ALB.

**Describe the enhancement/feature:**

Add native support the the 10.x helm charts to configure Identity CORS setting without using these undocumented env vars:
```
identity:
  env:
    - name: CORS_ALLOWED_ORIGIN_PATTERNS
      value: *test.com,*another*.com
    - name: CORS_ALLOWED_METHODS
      value: GET,POST
```
**Desired outcome and acceptance tests:**

```[tasklist]
### Tasks
- [ ]  I can reproduce Identity `Invalid CORS Request` error, e.g.: as shown in [SUPPORT-22437](https://jira.camunda.com/browse/SUPPORT-22437).
- [ ] I can configure Identity CORS setting in my values.yaml file without using env vars.
- [ ] After applying the new settings via `helm upgrade`, the Identity `Invalid CORS Request` error is resolved.
- [ ] No other Identity env vars are affected.
```

**Comment by aabouzaid** [comment]
@jessesimpson36 Suggested a really good idea for this: a way to append any extra config without rebuilding the whole config, as we do in `identity.configuration` (also for all apps).
