### ISSUE TITLE
[TASK] Use component image tag instead of the global tag

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2067]
## Related to

Epic: https://github.com/camunda/distribution/issues/148

## Overview

Now most of the Camunda application has its own patch version and it's expected to have this for all components.

## Actions

- [x] Targeted versions: 8.5 and 8.6
- [x] Set the global tag image `global.image.tag` to empty value.
- [x] Set the version for each component tag image e.g. `zeebe.image.tag`.
- [x] Ensure that Renovatebot uses the `docker` datasource, not the `github` datasource.

```[tasklist]
### Sub-tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2069
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2080
- [ ] https://github.com/camunda/camunda-docs/pull/3999
- [x] Inform Stakeholders.
```

**Comment by aabouzaid** [comment]
All actions are done :heavy_check_mark:

**Comment by aabouzaid** [comment]
I reopened this task to implement the support team's suggestion and add this change to the official docs (even if it's not a breaking change to ensure it's clear for the users).

**Comment by aabouzaid** [comment]
All sub-tasks are done.
