### ISSUE TITLE
[TASK] Rename Web Modeler PostgreSQL key

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2175]
## Related to

Epic: https://github.com/camunda/distribution/issues/230

## Overview

In the 8.5 cycle, we added a deprecation note for `postgresql` key that it will be renamed to `webModelerPostgresql`, which is consistent with the convention to name sub-components.

### Sub-tasks
- [x] Rename the `postgresql` key to `webModelerPostgresql`.
- [x] Add a [constraint](https://github.com/camunda/camunda-platform-helm/blob/1c57a8bec394bc6fe450fff89a95c31d9e68d031/charts/camunda-platform-8.8/templates/camunda/constraints.tpl#L145) to fail if the old key is used.
- [x] Add the change to the [official docs](https://github.com/camunda/camunda-docs/pull/6227), like the upgrade guide and announcement page

**Comment by aabouzaid** [comment]
This has been moved to the short cycle 8.7, which will be in Jan 2025.
