### ISSUE TITLE
[TASK] Upgrade dependency charts for Camunda 8.6 chart

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2200]
## Related to

Epic: https://github.com/camunda/distribution/issues/230

## Overview

We need to upgrade the dependency charts for the Camunda 8.6 chart (currently alpha).

## Actions

```[tasklist]
### Sub-tasks
- [x] Review all dependency charts for alpha and upgrade them.
- [x] Avoid breaking changes on the app level (i.e., we could upgrade the dep chart but keep the app version if possible).
- [x] Check the latest Elasticsearch support and update it in our Renovatebot config.
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2299
- [x] Added support for alpha renovatebot configure allowed versions of elasticsearch
```

**Comment by aabouzaid** [comment]
@drodriguez-305 FYI, we will need to upgrade the Keycloak chart to v22.2.0, which allows us to set the Keycloak PostgreSQL user password key ([PR](https://github.com/bitnami/charts/pull/29008), merged).

There is also a [PR](https://github.com/camunda/camunda-platform-helm/pull/2255) from Ben here to upgrade the Keycloak app.

**Comment by drodriguez-305** [comment]
Chart versions that were updated.

- postgresql - 14 -> 15
- web-modeler - 14 -> 15
- elasticsearch - 20.04 -> 21.3.11
- keycloak - 19.4.1 -> 22.2.1
