### ISSUE TITLE
[TASK] Increase Elasticsearch nodes from 2 to 3 by default

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2224]
## Related to

Epic: https://github.com/camunda/distribution/issues/230

## Overview

The ideal setup for Elasticseaech is 3 nodes. For local setup, we reduce the ES nodes to 1 anyway.

Relevant documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/high-availability-cluster-small-clusters.html

> Because it’s not resilient to failures, we do not recommend deploying a two-node cluster in production.

## Actions

```[tasklist]
### Sub-tasks
- [x] Change ES nodes from 2 to 3 by default for the Camunda 8.6 chart (alpha now).
- [x] Add `elasticsearch.master.podAntiAffinityPreset: hard`
- [x] Add the change to the official docs announcement and upgrade pages.
```

```[tasklist]
### PRs
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2298
- [ ] https://github.com/camunda/camunda-docs/pull/4255
```

**Comment by aabouzaid** [comment]
All actions are done :heavy_check_mark:
