### ISSUE TITLE
[TASK] Camunda 8.6 cycle relaese

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2404]
## Related to

Epic: https://github.com/camunda/distribution/issues/230

## Overview

This task for the Camunda 8.6 cycle release.

## Actions

```[tasklist]
### Sub-tasks
- [x] Ensure all renovatebot PRs merged
- [x] Update the chart structure (rename alpha to `8.6`, and update alpha dir versions).
- [x] Update please-release config.
- [x] Update renovatebot config.
- [x] Release Candidate (internal)
- [x] Release (customer facing)
```
```[tasklist]
### PRs
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2416
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2392
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2438
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2428
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2463
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2468
```
