### ISSUE TITLE
[EPIC] Renaming

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#241]
- [x] Repo renaming to Camunda platform helm
- [x] Add camunda-platform-helm chart, to make it already available before deprecating the old https://github.com/camunda/camunda-platform-helm/pull/261
   - [x] Replace all occurrences of camunda-cloud-helm and ccsm
   - [x] Release chart
- [x] Remove old ccsm charts
  - [x] Deprecate ccsm-helm and point to new https://github.com/camunda/camunda-platform-helm/pull/262
  - [x] Release old chart last time https://github.com/camunda/camunda-platform-helm/pull/262
  - [x] Remove ccsm chart https://github.com/camunda/camunda-platform-helm/pull/265

**Comment by Zelldon** [comment]
Done via #265
