### ISSUE TITLE
[TASK] Refactor Camunda Helm chart 8.7 to use unified Camunda image

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2477]
## Related to

Epic: https://github.com/camunda/distribution/issues/312

## Overview

Starting from Camunda 8.7, we will use the [unified Camunda](https://github.com/camunda/camunda) image, which will replace the orchestration components (Zeebe, Operate, Optimize, Tasklist, and later also Identity).

## Actions

```[tasklist]
### Sub-tasks
- [ ] Use the [unified Camunda](https://github.com/camunda/camunda) image.
- [ ] Disable old components (Zeebe, Zeebe Gateway, Operate, Optimize, Tasklist, but keep Identity for now).
- [ ] Ensure all components work together as expected, especially with the new `Execution Identity`.
```

**Comment by aabouzaid** [comment]
The task moved to 8.8 so I move it to the backlog.

**Comment by hisImminence** [comment]
@aabouzaid this task can be closed now, do you agree?

**Comment by aabouzaid** [comment]
Closing this as it's done and it's part of https://github.com/camunda/camunda-platform-helm/issues/3455
