### ISSUE TITLE
[TASK] Rename CI test client for Identity

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2482]
## Related to

Epic: https://github.com/camunda/distribution/issues/312

## Overview

We need to rename the CI test client for Identity to make it easier to be used by different teams.

## Actions

```[tasklist]
### Sub-tasks
- [x] Rename the CI test client for Identity from `venom` to `test`.
- [ ] Remove any extra client provided by other teams in the [Distro GHA workflow](https://github.com/camunda/camunda-platform-helm/blob/main/docs/gha-workflows.md).
- [x] QA E2E repo is adjusted
- [x] Camunda/camunda repo is adjusted
```

**Comment by hisImminence** [comment]
Also mentioned here: https://github.com/camunda/camunda-platform-helm/issues/2528

**Comment by hisImminence** [comment]
Waiting for alpha release to be finished

**Comment by hisImminence** [comment]
After this is merged please check with QA is the 8.8 build can be resolved https://github.com/orgs/camunda/projects/33/views/5?pane=issue&itemId=100468400&issue=camunda%7Ccamunda-platform-helm%7C3075

**Comment by aabouzaid** [comment]
I reopened the issue as we reverted the changes.
