### ISSUE TITLE
[TASK] Implement the unified Orchestration Core in the 8.7 Alpha chart

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2525]
## Related to

Epic: https://github.com/camunda/distribution/issues/331

## Overview

Implement the unified Orchestration Core in the 8.7 Alpha chart and remove the following individual components:

- Zeebe / Zeebe Gateway
- Operate
- Optimize
- Tasklist
- Execution Identity (it was disabled by default in 8.6)

## Actions

```[tasklist]
### Sub-tasks
- [ ] The new component should use [camunda/camunda](https://hub.docker.com/r/camunda/camunda) image.
- [ ] The new component is called `core`.
- [ ] The new component should be a `StatefulSet` .
```

```[tasklist]
### PRs
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2554
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2581
```

**Comment by aabouzaid** [comment]
> @aabouzaid could you give progress update here and answer the following questions?
> 
> cc. @Zelldon
> 
> > What was our plan for migrating or keeping the values files for the Helm charts? Will we have a breaking change in how we configure the different components?

We will definitely make breaking changes. We have planned the ones since 8.5, and the new ones will come with the 8.7 unified release.

Regarding the updates, I reached a state today where I can render the chart with the new structure, and I will give it a live test on Monday.

**Comment by aabouzaid** [comment]
Closing this PR as all tasks are done.

The Connectors component has a known limitation, which the team has discussed. The Connectors app doesn't work with the new setup (It should be fixed in 8.7 Alpha 2.)
