### ISSUE TITLE
[ENHANCEMENT] Enable QA To Create the Helm Chart with OpenSearch via GHA

### ISSUE THREAD

**Issue by slolatte** [camunda/camunda-platform-helm#2626]
**Describe the use case:**

I am currently working on expanding the [cross component test suite](https://github.com/camunda/c8-cross-component-e2e-tests) to cover OpenSearch. For context, please see the [following ticket](https://github.com/camunda/c8-cross-component-e2e-tests/issues/484).  However, I am running into some [Helm Chart installation errors](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12273260721).  I have followed the setup instructions in [our documentation](https://docs.camunda.io/docs/self-managed/setup/guides/using-existing-opensearch/), and using the [OpenSearch instance provided by infra](https://confluence.camunda.com/pages/viewpage.action?pageId=178590693). 

**Describe the enhancement/feature:**

For more context, please see the following [Slack thread](https://camunda.slack.com/archives/C06BN4SRB6C/p1733143667041789). 

**Desired outcome and acceptance tests:**

This will enable QA on a nightly basis and during release time, to test OpenSearch.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/c8-cross-component-e2e-tests/pull/574
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2764
- [ ] Clean up DB after nightly runs
```

**Comment by hamza-m-masood** [comment]
I will create an OpenSearch instance for QA team to use. The database must be wiped via a github actions workflow before every nightly run.

**Comment by hamza-m-masood** [comment]
OpenSearch instance is now created. 
I will work on modifying the github actions workflow now.

**Comment by hamza-m-masood** [comment]
Please note: This github action workflow can only be run alone. It will not be possible to run many instances of this github action at the same time because the DB would need to be wiped before every run.

**Comment by hamza-m-masood** [comment]
I can trigger a run from the e2e QA repo with the correct values.yaml so the platform uses OpenSearch as a DB. The problem that I have just discovered is that our integration tests are not built to support DBs other than elasticsearch. I see that two pre-flight tests are failing because of the missing elasticsearch pods:
1. `TEST-Liveness`
2. `TEST-Readiness`

The core test suite will probably have more failing tests, but I can only see that when I fix the pre-flight tests.

Another PR must be created to fix these integration tests and support other databases.

**Comment by slolatte** [comment]
@hamza-m-masood Thanks for the update and for the support with this!

**Comment by hamza-m-masood** [comment]
PR created: https://github.com/camunda/camunda-platform-helm/pull/2764
It is a WIP

**Comment by slolatte** [comment]
@hamza-m-masood Would you be able to provide a status update on this ticket?

**Comment by hisImminence** [comment]
We will leverage infrastructures teams infrastructure and start with easier testing szenarios. Once they are done, we will continue here.

**Comment by mschoe** [comment]
@hisImminence is there any progress here? For the upcoming 8.7 release I would like to have this environment integrated into our automated tests. Is there an ETA?

**Comment by slolatte** [comment]
@mschoe I believe @yevhen-cap is working on implementing this and the correct ticket to track this can be found [here](https://github.com/camunda/c8-cross-component-e2e-tests/issues/645)

**Comment by hisImminence** [comment]
@slolatte, should we keep this open or close it too (related to https://github.com/camunda/camunda/issues/30199)? IMO this is not provided anymore by the distro team but directly via @yevhen-cap :)

**Comment by slolatte** [comment]
Yes we can close this as it has been completed :)
