### ISSUE TITLE
[TASK] Add integration test for combined Ingress setup

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#408]
**Describe the use case:**

In PR no. #399 we introduced a combined Ingress setup, and we have unit tests for it but need to have an integration test for the new feature. However, because we didn't test ingress before and it needs some prerequisites, the integration test has been postponed.

**Describe the enhancement/feature:**

We need to test if the endpoints of combined Ingress setup are working as expected. 

**Desired outcome and acceptance tests:**

- Add integration test for combined Ingress setup for all supported platforms (e.g. Stock Kubernetes, OpenShift, and EKS).
- The test should include at least Nginx Ingress. Also, it could have some other Ingresses like AWS LB ingress.

**PRs:**
- [x] https://github.com/camunda/camunda-platform-helm/pull/728
- [x] Accessing Ingress URL with redirection.
- [ ] Test login web pages (enter username and password).

**Comment by aabouzaid** [comment]
This task is partially done by #728
The last part of it is accessing the web pages and check the login forum as mentioned here:

> TODO: Use Venom "web" module to test actual login. It's easy but requires "PhantomJS"
> which is not available on Alpine, so it needs to be installed first.

https://github.com/camunda/camunda-platform-helm/blob/fcf6756d9f8ed6096881a376302d4e39c3764b74/charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml#L63

**Comment by aabouzaid** [comment]
As discussed in the grooming, we are fine with the current level of testing and will see how the QA team wants to go with more testing.

So this task is considered done.
