### ISSUE TITLE
Release checklist - Camunda Platform Helm chart v8.2

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#543]
This a checklist of changes that should be done before releasing the next minor version 8.2 (around April 2023).

**General (DRI @aabouzaid):**
- [x] https://github.com/camunda/camunda-platform-helm/issues/392
  - [x] https://github.com/camunda/camunda-platform-helm/pull/601
- [x] https://github.com/camunda/camunda-platform-helm/issues/465
  - [x] https://github.com/camunda/camunda-platform-helm/pull/602
- [ ] https://github.com/camunda/camunda-platform-helm/issues/611
- [x] https://github.com/camunda/camunda-platform-helm/pull/603
- [x] https://github.com/camunda/camunda-platform-helm/pull/596
- [ ] https://github.com/camunda/camunda-platform-helm/pull/600
- [x] https://github.com/camunda/camunda-platform-helm/pull/610

**WebModeler (DRI @jfriedenstab ):**
- [x] Make it part of the main chart instead of a sub-chart (we will migrate all components one by one).
  - done with #584
- [x] Think about changing the may key to `webModeler` instead of `web-modeler` because keys with dash are always problematic in Helm/YAML.
  - done with #584
- [x] https://github.com/camunda/camunda-platform-helm/pull/569.
  - [x] Ensure that WebModeler works with HTTP/HTTPS in separated and combined Ingress (those are 4 scenarios).
- [x] Update the architecture diagram with Web Modeler in it:
  - [x] in-repo
    - #593
  - [x] https://helm.camunda.io/
    - #594
  - [x] official docs
    - https://github.com/camunda/camunda-platform-docs/pull/1849
- [x] Remove "beta" status in README file
  - #599

**Connectors (DRI @igpetrov):**
- [x] https://github.com/camunda/camunda-platform-helm/pull/566
- [x] https://github.com/camunda/camunda-platform-helm/pull/583
  - [x] Add all readiness, liveness, and startup probs (readiness should be enabled by default).
  - [x] Add Ingress config.
  - [x] Add unit and integration tests.
- [x] Update the architecture diagram in this repo and official docs.
  - [x] https://github.com/camunda/camunda-platform-helm/pull/604
  - [x] https://github.com/camunda/camunda-platform-helm/pull/605
  - [x] https://github.com/camunda/camunda-platform-docs/pull/1911

**Comment by aabouzaid** [comment]
@jfriedenstab I've added a section for WebModeler not to forget anything before the next release.
Feel free to add anything to the list.

**Comment by aabouzaid** [comment]
@igpetrov could you please link to the Connectors issues here to make it clear what's done and what's not?

**Comment by jfriedenstab** [comment]
> Remove private container repo access when the WM image is public

@aabouzaid I removed this point from the list as we will not make the Web Modeler images public.

**Comment by aabouzaid** [comment]
All checklist items are done expect 2 unblocker ones I will work on them shortly:
- https://github.com/camunda/camunda-platform-helm/issues/611
- https://github.com/camunda/camunda-platform-helm/pull/600 (there was an issue in the index, so I reverted it).

Thus, I've released [Camunda Platform Helm chart v8.2](https://github.com/camunda/camunda-platform-helm/pull/610) :rocket: 

Thanks for your great effort @jfriedenstab and @igpetrov :clap:
