### ISSUE TITLE
[EPIC] Support Elasticsearch 8

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#655]
**Describe the use case:**

Support Elasticsearch 8 since it's already in the Camunda Platform 8 apps [supported environments](https://docs.camunda.io/docs/reference/supported-environments/). 

**Describe the enhancement/feature:**

**Desired outcome and acceptance tests:**

- [x] https://github.com/camunda/camunda-platform-helm/issues/897
  - [x] Support the Camunda Platform 8 Helm chart with at least Elasticsearch 8.7.x
  - [x] ILM is configurable
  - [x] In-repo docs
  
 Docs Task: https://github.com/camunda/camunda-platform-helm/issues/924

**Related to:**
[SUPPORT-16899](https://jira.camunda.com/browse/SUPPORT-16899)

**Comment by aabouzaid** [comment]
@daniel-ewing based on the [ES 8.6 release notes](https://www.elastic.co/guide/en/enterprise-search/master/release-notes-8.6.0.html) there is no breaking changes. So probably ES 8.5 will work the same, but it could be added in another iteration if needed.

**Comment by hisImminence** [comment]
Hey @chrstphfrtz, 

sry for the late update! ELS 8.7+ will be supported starting with the next minor Camunda Platform release 8.3.0 [in October](https://camunda.com/release-policy/)

**Comment by aabouzaid** [comment]
I'm closing this epic since the changes related to ES8 and in-repo docs have been merged.

The final step is creating the upgrade guide in the Camunda docs which is tracked in https://github.com/camunda/camunda-platform-helm/issues/924
