### ISSUE TITLE
[ENHANCEMENT] Rolling upgrades in each C8 component

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#838]
**Describe the use case:**

A couple of tickets / questions have brought this to my attention.   We are not properly supporting rolling upgrades as documented by https://docs.camunda.io/docs/self-managed/about-self-managed/. 

In Zeebe's case, they recommend performing a backup of the data prior to performing an upgrade
https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/update-zeebe/

In Optimize, I learned that users actually cannot upgrade from 8.1.4 to 8.2.10 without manually executing 
```
./optimize.sh --upgrade
```
source: https://docs.camunda.io/optimize/self-managed/optimize-deployment/migration-update/instructions/

There is an alternative mode of Optimize where if  you set your command to 
```
./optimize-startup.sh --upgrade
```
Then optimize will run after it performs the upgrade on startup.  So why not just override the command and perform that upgrade prior to each execution?

**Describe the enhancement/feature:**
Each component in the helm chart should perform rolling upgrades if the application component (zeebe, optimize, operate, ...) supports it.  Which also means that as part of this task, an investigation should be done in each application component to see if they support rolling upgrades.

**Desired outcome and acceptance tests:**

```[tasklist]
### Tasks
- [ ] Zeebe is checked for support with rolling upgrades
- [ ] Operate is checked for support with rolling upgrades
- [ ] Optimize is checked for support with rolling upgrades
- [ ] Tasklist is checked for support with rolling upgrades
- [ ] Web Modeler is checked for support with rolling upgrades
- [ ] Identity is checked for support with rolling upgrades
- [ ] Each component's command  is replaced with a version that supports running the upgrade prior to starting up the program.
```

Related Support Tickets: [SUPPORT-17876](https://jira.camunda.com/browse/SUPPORT-17876)

**Comment by jessesimpson36** [comment]
Related: https://github.com/camunda/distribution/issues/96

**Comment by jonathanlukas** [comment]
Regarding Optimize: We documented the approach of using an migration init container: 

https://docs.camunda.io/optimize/next/self-managed/optimize-deployment/migration-update/instructions/#32-automatic-update-execution-optimize-320

There might be some docs like this for other components as well.

We should keep docs and distro aligned.

**Comment by jessesimpson36** [comment]
Thank you @jonathanlukas  for pointing me to that doc.  I found that part of the docs was even in there since C7!
https://docs.camunda.org/optimize/3.6/technical-guide/update/#3-2-automatic-update-execution-optimize-3-2-0

Up till now, it was hard to really come to a conclusion whether we should include that upgrade command as an init container or not, but with that documentation, it REALLY seems like we should have it.
