### ISSUE TITLE
[TASK] Test upgrade of all Camunda supported versions

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#959]
**Related to:**

distribution/issues/125

**Overview:**

Currently, we are just testing the upgrade from the latest released Helm chart (e.g., the latest release is 8.5.0 we test it against 8.5.1). We also need to test other supported versions, like from the latest 8.5 to the latest 8.8.

**Actions:**

### Tasks
- [x] https://github.com/camunda/camunda-platform-helm/pull/1971
- [x] https://github.com/camunda/camunda-platform-helm/pull/4300
- [ ] https://github.com/camunda/camunda-platform-helm/pull/4354

**Comment by jessesimpson36** [comment]
I don't think this is related to what @theburi wanted for the [product-hub ticket](https://github.com/camunda/product-hub/issues/1957), and this is somewhat dependent on the implementation of https://github.com/camunda/distribution/issues/265 . 

I'd recommend we wait on this until the next release patch release or two.

**Comment by hisImminence** [comment]
> I don't think this is related to what [@theburi](https://github.com/theburi) wanted for the [product-hub ticket](https://github.com/camunda/product-hub/issues/1957), and this is somewhat dependent on the implementation of [camunda/distribution#265](https://github.com/camunda/distribution/issues/265) .
> 
> I'd recommend we wait on this until the next release patch release or two.

@aabouzaid would it make sense to move this task to the ticket https://github.com/camunda/distribution/issues/148 and close the parent ticket of this one then https://github.com/camunda/distribution/issues/125?

**Comment by aabouzaid** [comment]
@hisImminence That makes sense, done :heavy_check_mark: 
And actually, part of the issue has been fixed in https://github.com/camunda/camunda-platform-helm/pull/1971

**Comment by hamza-m-masood** [comment]
@jessesimpson36 would it be possible if you could do the upgrades with scenarios I have created?

What I mean is that you could have multiple upgrade paths. For example, upgrading with multitenancy enabled from 8.3 all the way to 8.8. Or upgrading with OpenSearc enabled. What do you think?

**Comment by hisImminence** [comment]
OMG! I had the same thought when we [last minute discovered](https://camunda.slack.com/archives/C05H6R2DXUY/p1747031466286739) we would have introduced breaking change! Having the upgrade tests including several scenarios could have catch this early on I suppose!
